set(CMAKE_BUILD_TYPE "Release" CACHE STRING "")

set(BUILD_SHARED_LIBS On  CACHE BOOL "")
set(BUILD_TESTING     Off CACHE BOOL "")

set(ENABLE_TESTS      Off CACHE BOOL "")
set(ENABLE_GTEST      Off CACHE BOOL "")
set(ENABLE_MPI        Off CACHE BOOL "")
